{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microservice.serviceAccountName" . }}
  labels:
{{ include "microservice.labels" . | nindent 4 }}
{{- end -}}
