---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.fullname" . }}
type: Opaque
data:
  username: {{ template "couchbase-cluster.username" . }}
  password: {{ template "couchbase-cluster.password" . }}
